### ISSUE TITLE
As of 0.13.2 `OPA: Evaluate Package` command stopped working.

### ISSUE THREAD

**Issue by DrMagPie** [open-policy-agent/vscode-opa#107]
Hi,

When extension updated to version `0.13.2` the `OPA: Evaluate Package` command stopped working.
Initially I thought it was an issue with my computer, but when my colleague mentioned same problem we started to investigate this deeper.

Reverting extension to previous version fixes the problem.

I looked what was changed between versions, and tried to change it back. https://github.com/open-policy-agent/vscode-opa/compare/v0.13.1...v0.13.2#diff-e0d540e507c2b863faa5403e7a59613113327a3ef57d1e0dcde2e36fa1c0fb36L313

It seems that setting options/env vars is breaking it.
https://github.com/open-policy-agent/vscode-opa/blob/f7d8def71f3701534bacd8dc7918293a507ba2c4/src/opa.ts#L317

v0.13.2
![image](https://github.com/open-policy-agent/vscode-opa/assets/23652900/0f2926c9-a3ee-4def-9aed-ffe210c3d0c6)

v0.13.2 with manually edited of extension code to revert `cp.spawn`
![image](https://github.com/open-policy-agent/vscode-opa/assets/23652900/9b70b00b-451c-418e-8635-fcf4c9a4077e)

![image](https://github.com/open-policy-agent/vscode-opa/assets/23652900/a7d81d34-282b-45b6-8b9c-59b0db3bffc2)

v0.13.1
![image](https://github.com/open-policy-agent/vscode-opa/assets/23652900/6620a661-b0d1-4a94-b57a-bf6e55b89609)

### VS Code
Version: 1.87.0 (user setup)
Commit: 019f4d1419fbc8219a181fab7892ebccf7ee29a2
Date: 2024-02-27T23:41:44.469Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22000

### OPA
Version: 0.62.0
Build Commit: 1d0ab93822e83a4165c78372a7fb4c05e14a8bca
Build Timestamp: 2024-02-29T17:07:11Z
Build Hostname: 80718c8d5221
Go Version: go1.22.0
Platform: linux/amd64
WebAssembly: unavailable

### OS - WSL
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy

**Comment by anderseknert** [comment]
Hi there, and thanks for reporting this! I guess we were too busy testing the Regal integration that we might have let this one slip through.

Would you have time to look into this @mxsph , or should someone else pick it up?

**Comment by mxsph** [comment]
> Would you have time to look into this @mxsph , or should someone else pick it up?

Yes, I can have a look at it 👍 It looks like it's because node interprets the `PATH` variable differently when you pass `options.env` (https://nodejs.org/api/child_process.html#child-process). Which then probably leads to the `opa executable` no longer being found on some systems. That's why this change worked for me. I will test this theory and then create a PR.

**Comment by anderseknert** [comment]
Unrelated, but I forgot to say — what an excellent bug report @DrMagPie 👏
