### ISSUE TITLE
Feature request: print width

### ISSUE THREAD

**Issue by shinebayar-g** [open-policy-agent/vscode-opa#114]
It's messing up multi line strings and making it a really long line. Is it possible to have some kind of character limit per line?

Before
![image](https://github.com/open-policy-agent/vscode-opa/assets/3091558/e57c294c-bc6c-4459-a75b-1d81f719ed6f)

After
![image](https://github.com/open-policy-agent/vscode-opa/assets/3091558/a9e3b18d-bedb-46e0-9e70-f0267c023165)

**Comment by anderseknert** [comment]
Oh, and btw, it looks like you are using `+` to concatenate strings? That doesn't work in Rego at this point at least. Are you not seeing parser errors due to that? 🤔

**Comment by shinebayar-g** [comment]
Oh I see. Yeah I use `editor.formatOnSave`, I guess this is more related to `opa fmt` rather than the extension. Thanks so much for the workaround. While I haven't tried to deploy `+` concatenated strings, I didn't receive error from extension.

**Comment by anderseknert** [comment]
Yeah, by all means, feel free to open an issue about line length and formatting in the OPA repo 👍 I'll close this issue here as we can't do much about it unless it's fixed in the formatter itself.

Thanks!
