### ISSUE TITLE
Tool tips for built-in functions

### ISSUE THREAD

**Issue by tsandall** [open-policy-agent/vscode-opa#17]
It would be really nice if we could pop-up tool tips for built-in functions in Rego. This would require some work in upstream OPA to avoid falling out-of-sync. E.g., upstream OPA could publish a built-in function registry with parameter descriptions.

**Comment by anderseknert** [comment]
With the next release of OPA, we'll have not just the name and argument types for the built-ins, but even the names, allowing us to provide rich documentation right in the editor. We should leverage this for a great policy authoring experience!

**Comment by tsandall** [comment]
Now that we have the built-in function signatures available as a data source this is more feasible: https://github.com/open-policy-agent/opa/blob/main/builtin_metadata.json

**Comment by anderseknert** [comment]
This is now available via the [Regal](https://docs.styra.com/regal) language server. To have it enabled, simply allow the extension to install Regal, or do it by other means, like `brew install styrainc/packages/regal`. 

![320480613-56903a03-2adc-4ee6-97d1-310c536fe1ee](https://github.com/open-policy-agent/vscode-opa/assets/510711/b640bee8-b5d9-4881-b3fb-a4b79aa22879)
