### ISSUE TITLE
Syntax errors are hidden on evaluation

### ISSUE THREAD

**Issue by timothyhinrichs** [open-policy-agent/vscode-opa#19]
It's easy for users to miss syntax error warnings, and sometimes the warnings don't appear at all when running Evaluate.  People just see the dreaded "No results" and assume it's something wrong with the policy logic.

One option would be to display syntax errors in the Output.

**Comment by anderseknert** [comment]
With the Regal extension enabled, parse errors will be reported and highlighted as you work on your policy. For that reason, I think we can close this issue now as fixed. 

Let me know if there's a good reason why we still need this at the time of evaluation too, and I'll reopen.
