### ISSUE TITLE
Allow for using OPA in docker image

### ISSUE THREAD

**Issue by patrick-east** [open-policy-agent/vscode-opa#25]
Rather than having the OPA binary installed locally it could be convienent to have the plugin just do `docker run`'s with the opa image and mount the workspace into the image.

This would probably require a couple of config options in the plugin. One to enable using docker and one to specify the image. Maybe we take some shortcut and only add the image, or if the path to opa is like docker:///blah we assume it should use the image and run a container?

**Comment by charlieegan3** [comment]
We're decided to close this one. We have recently added support for Regal and are focused on the use of local binaries as the means for running OPA and linting tooling.

The plugin's code for managing installed dependencies is already quite involved and supporting a single mode of OPA execution helps keep some of this in check.

For others, please comment if you a good use case to make this worthwhile again and we can consider it.
