### ISSUE TITLE
Unable to evaluate packages - too many open files ERROR

### ISSUE THREAD

**Issue by rawc0der** [open-policy-agent/vscode-opa#40]
Hi,

I am encountering the following error in my vscode workspace if I try evaluating any packages:
```
{
  "errors": [
    {
      "message": "loading error: bundle file:///***: bundle read failed: failed to open file /***/node_modules/core-js/stable/clear-immediate.js: open /***/node_modules/core-js/stable/clear-immediate.js: too many open files"
    }
  ],
  "metrics": {
    "timer_rego_load_bundles_ns": 453710894
  }
}
```
Same error after changing max file descriptors on my workstation and tweaking other kernel settings.
Running the formatter works but no means to even evaluate policy fragment selection.

I am not sure if this is due to a large number of policies loaded in the `policy` folder... or if the plugin is reading all the other `.yaml/json` files in the directory.

settings.json looks like this:
```
  "opa.bundleMode":"true",
  "opa.roots": "${workspaceFolder}/policies/lib"
```
If there is indeed any limit of `YAML` or `rego` expressions imposed by other packages, then what are the setbacks for policy eval..

If anybody encountered this kind of issue, please share your findings here.
Thanks.

**Comment by anderseknert** [comment]
Hi @rawc0der 👋  And sorry for not getting back to you before! 

This issue was fixed in OPA some releases back: https://github.com/open-policy-agent/opa/issues/3777, so I'll close this one as resolved, but please let me know if you're still seeing this using a recent version of OPA and I'll reopen and take a look.
