### ISSUE TITLE
Cannot resolve ${workspaceFolder} in opa.path in workspace settings.json

### ISSUE THREAD

**Issue by aklefdal** [open-policy-agent/vscode-opa#44]
I'm trying to have a `settings.json` file in the workspace where I set `opa.path` to a specific `opa.exe` in the workspace.

I'm on windows, having a custom system for authorization, and I'm running the command `OPA: Test Workspace`

This works fine, all tests are run:
```json
{
    "opa.path": "C:/src/my-org/my-repo/opa.exe",
    "opa.roots": [
        "${workspaceFolder}/my-rules"
    ]
}
```

This does not work, only an empty OPA output window:
```json
{
    "opa.path": "${workspaceFolder}/opa.exe",
    "opa.roots": [
        "${workspaceFolder}/my-rules"
    ]
}
```

Note that the `opa.roots` setting works fine. If set it to a non-existing folder, it complains.

What am I doing wrong?

**Comment by tsandall** [comment]
This might be related to #46. We would have to look at the resolved path that is being used to run the subprocess.

**Comment by tsandall** [comment]
OK, so `${workspaceFolder}` is only supported on `opa.roots` it's not supported on `opa.path`. That's why it doesn't work.
