### ISSUE TITLE
OPA + custom functions dont work in plugin

### ISSUE THREAD

**Issue by kirk-patton** [open-policy-agent/vscode-opa#48]
I recently created an extension function following the instructions [here](https://www.openpolicyagent.org/docs/latest/extensions/).  My custom function works with the unit tests, and I can eval it with the resulting binary. But when I try to eval it in vsCode, I get an empty  output window. _I made sure my path put my custom opa at the beginning._

```
package foo


foo = limit {
	cpuRequest := "50m"
	cpuLimit := "55m"
	limit := k8s_util.CalculateDefaultCPULimit(cpuRequest,cpuLimit,"")
}
```

cmdLine

```
>~/bin/opa eval 'cpuRequest := "500m"
        cpuLimit := ""
        limit := k8s_util.CalculateDefaultCPULimit(cpuRequest,cpuLimit,"")'
util.CalculateCPULimit inputRequestKey: 500m
{
  "result": [
    {
      "expressions": [
        {
          "value": true,
          "text": "cpuRequest := \"500m\"",
          "location": {
            "row": 1,
            "col": 1
          }
        },
        {
          "value": true,
          "text": "cpuLimit := \"\"",
          "location": {
            "row": 2,
            "col": 2
          }
        },
        {
          "value": true,
          "text": "limit := k8s_util.CalculateDefaultCPULimit(cpuRequest,cpuLimit,\"\")",
          "location": {
            "row": 3,
            "col": 2
          }
        }
      ],
      "bindings": {
        "cpuLimit": "",
        "cpuRequest": "500m",
        "limit": "4"
      }
    }
  ]
}
```

_I also tried setting "opa.path" to point directly to my binary.  It made no difference._

**Comment by kirk-patton** [comment]
<img width="1680" alt="Screen Shot 2021-07-10 at 1 13 36 PM" src="https://user-images.githubusercontent.com/3884606/125175400-ab3e9180-e180-11eb-8733-8a4c0c79ad92.png">

**Comment by kirk-patton** [comment]
<img width="1674" alt="Screen Shot 2021-07-10 at 1 13 36 PM" src="https://user-images.githubusercontent.com/3884606/125175484-5f401c80-e181-11eb-8e78-356fb6ed104b.png">

**Comment by tsandall** [comment]
I just tested this out myself and didn't run into any issue: 
![image](https://user-images.githubusercontent.com/238885/125356508-263baf80-e31b-11eb-9a0c-de9e85e4a652.png)

If vscode is using the wrong `opa` executable, then you should see an error in the Output panel (the output on the right is stale):

![image](https://user-images.githubusercontent.com/238885/125356598-44a1ab00-e31b-11eb-82e5-e20688666edb.png)

**Comment by kirk-patton** [comment]
@tsandall  Yes, my plugin is otherwise working fine.  Unit tests pass and other policies evaluate just fine.  Before I opened the issue I tried setting "opa.path" to the stock version of OPA and then to my build to see the difference in behavior.  As you noted, if I tried to eval my function while pointed to stock, I get an error that the function is not known. When using my build, the output window is just blank.

**Comment by kirk-patton** [comment]
<img width="1680" alt="Screen Shot 2021-07-12 at 3 59 50 PM" src="https://user-images.githubusercontent.com/3884606/125366211-8554f080-e32a-11eb-86df-092db6b6f96b.png">

**Comment by kirk-patton** [comment]
@tsandall I installed vsCode fresh on my other mac.  I then copied the custom "opa" I built, with my function to, that mac.  I see the same issue.  When I eval my function from vsCode, no output.  When I run "opa eval ..." from the command line, I get the expected output.

**Comment by kirk-patton** [comment]
I figured out the issue.  I had a debug statement in my plugin code that was using fmt.Println().  I commented it out and the plugin now returns the expected output.

<img width="1680" alt="Screen Shot 2021-07-13 at 8 47 29 AM" src="https://user-images.githubusercontent.com/3884606/125483660-25d9ce69-950f-4d2c-817f-223bc2505f73.png">

Thank you!
Kirk

**Comment by tsandall** [comment]
Ah, glad you figured it out. Stray println statements will definitely break the VS code extension because it's parsing the output as JSON.
