### ISSUE TITLE
Opa Configuration

### ISSUE THREAD

**Issue by eqvis** [open-policy-agent/vscode-opa#51]
Hi,
I'm using this plugin successfully for some time now. And I miss a possibility to start OPA with a configuration (option `--config-file my-config.yml` as command line argument). Is this feature really missing or can I add this to the OPA-command-line anyhow?

Thank you for your good work!
Eqvis

PS: I want to enable logging via config-file

**Comment by anderseknert** [comment]
Closing, as I don't think there's much to do here.
