### ISSUE TITLE
Markdown table looks broken in Marketplace

### ISSUE THREAD

**Issue by anderseknert** [open-policy-agent/vscode-opa#55]
Not sure if this is sourced automatically from the README or manually copy-pasted, but the table—which looks alright in the Github view—looks borked in the Marketplace. We should fix this for a better first impression for those that discover the plugin there.

![Screenshot 2022-01-07 at 15 01 10](https://user-images.githubusercontent.com/510711/148555092-21bcee72-c2b7-4ab5-9ac8-e810c9520bdf.png)

**Comment by johanfylling** [comment]
I believe this is fixed in the `master` branch. We can confirm once the next version is published.

**Comment by anderseknert** [comment]
Yeah, at least if that is synced automatically from the README. Could be a manual copy-paste is needed?

**Comment by johanfylling** [comment]
This was fixed with the `0.10.0` release.
