### ISSUE TITLE
No output on OPA evaluate package/selection

### ISSUE THREAD

**Issue by ytra** [open-policy-agent/vscode-opa#69]
OS: MacOS Monterey
VScode: 1.64.2
vscode-opa-plugin: 0.10.0 (tried 0.9.0 with same results)

VScode starts a output.json without any results. This is checked with policy files that do work in the rego playground.

**Comment by anderseknert** [comment]
Hey @ytra! And thanks for reporting this. I just took a look and I seem to have the same issue.
