### ISSUE TITLE
No syntax highlighting for raw strings in VSCode

### ISSUE THREAD

**Issue by stevend-15** [open-policy-agent/vscode-opa#78]
It seems the OPA extension on VSCode does not include syntax highlighting for raw string i.e.

![image](https://user-images.githubusercontent.com/66806985/178623481-ebc2f49d-db47-4f4f-a8e7-68a4576b145f.png)

Not sure what IDE was used in [this similar issue](https://github.com/open-policy-agent/opa-idea-plugin/issues/121) but I'm assuming it was not VSCode.

**Comment by oren-zohar** [comment]
> Not sure what IDE was used in https://github.com/open-policy-agent/opa-idea-plugin/issues/121 but I'm assuming it was no VSCode

Sorry for not being clear, it was Pycharm.
