### ISSUE TITLE
vscode-opa conflict with code formatter key binding

### ISSUE THREAD

**Issue by bluebambu** [open-policy-agent/vscode-opa#79]
Hi, previously I was working on .rego files with vscode-vim and python formatter, using vim "==" to do formatting and things are working. Today I tried to install vscode-opa and it disable the "==" operation. I uninstall vscode-opa and it works again. There is a conflict between them. Is there a solution to it?  Thanks.

**Comment by anderseknert** [comment]
Hi there! And sorry for taking almost 2 years to respond 😬 Only just recently coming back for some increased development efforts in this repo.

This extension doesn't set any keybindings on its own, but the formatter shortcut is a global one. The default value should be something like:

```json
{
    "key": "shift+alt+f",
    "command": "editor.action.formatDocument",
    "when": "editorHasDocumentFormattingProvider && editorTextFocus && !editorReadonly && !inCompositeEditor"
}
```

Perhaps this is possible to override, adding `editorLangId == rego` or `editorLangId != rego` to the `when` expression to have it included/excluded, or to create a distinct shortcut for Rego alone. But I don't think there's anything we can do on our side to change this. Will close for now, but happy to reopen if someone has better ideas than I do.
