### ISSUE TITLE
opa.path in settings.json doesn't seem to work

### ISSUE THREAD

**Issue by alexbozhenko** [open-policy-agent/vscode-opa#87]
Hi.

When I try to set
```
"opa.path": "${workspaceFolder}/scripts/lint/opa",
```
in `settings.json`, I am getting the following error under "Extension Host (Remote)" tab in vscode:

```  
2023-04-18 18:51:18.666 [error] Error: spawn opa ENOENT
at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
at onErrorNT (node:internal/child_process:478:16)
at processTicksAndRejections (node:internal/process/task_queues:83:21)
```
So based on https://github.com/microsoft/vscode/issues/2809 and https://code.visualstudio.com/docs/editor/variables-reference#_is-variable-substitution-supported-in-user-and-workspace-settings
Does it seem like it is actually not supported?

**Comment by anderseknert** [comment]
The `${workspaceFolder}` variable is supported: https://code.visualstudio.com/docs/editor/variables-reference#_predefined-variables

I'm not sure what might cause the error. Have you `chmod +x` the `opa` binary?

**Comment by alexbozhenko** [comment]
@anderseknert thanks for looking into this!
I just confirmed one more time, that this does not work:
```
    "opa.path": "${workspaceFolder}/opa",
```
but this does:
```
    "opa.path": "/full/path/to/opa",
```

My reading is 
![image](https://user-images.githubusercontent.com/5295986/233765531-11b81478-478b-4dda-a045-00acc202cddf.png)
means that this variable is not supported in settings.json

Could you please try setting the path using `workspaceFolder`, and confirm that it works for you?

**Comment by anderseknert** [comment]
Trying it here, the error message suggest the variable is resolved:

<img width="438" alt="Screenshot 2023-04-23 at 22 58 45" src="https://user-images.githubusercontent.com/510711/233865979-3bcf9539-3bca-4472-a4a4-9a71d2f5378b.png">

It still doesn't _work_ though, for reasons I'd need more time to investigate, but I don't think`${workspaceFolder}` resoultion is the problem here.

**Comment by anderseknert** [comment]
Replacing it with the absolute path without the `file://` protocol works, as you suggested... so the fix is likely to just have that removed.

**Comment by anderseknert** [comment]
PR up https://github.com/open-policy-agent/vscode-opa/pull/88

**Comment by alexbozhenko** [comment]
Thanks for fixing it, Anders!
