### ISSUE TITLE
Go to Defintion, Find All References and Debug

### ISSUE THREAD

**Issue by Ronnie-personal** [open-policy-agent/vscode-opa#95]
Hi vscode-opa maintainers, 

Correct me if I'm wrong, but currently, the OPA VSCode Extension does not support  'go to definition,' 'find all references,' or debugging (step over, step into).

OPA is becoming popular for API and application authorization, and API/application authorization is coded in the Rego language. The above-mentioned features are necessary for the developers to effectively author and debug authorization as code.

Do you have any roadmap on these features?

Thank you!

**Comment by anderseknert** [comment]
Hi Ronnie! Good to see you here as well 🙂 

IIRC some limited version of "go to definition" is supported, but you're right about the other features not currently being supported.

Proper debugging would need support in OPA, I think, but it's obviously doable provided "some" effort :) 

Not a whole lot of action in general in our editor integrations recently, and I hope that's something we'll be able to change soon. If there's anything you'd like to investigate or work on in this space, that'd be very welcome!

**Comment by Ronnie-personal** [comment]
Hi @anderseknert 
Thanks for the information.
I have some bandwidth to contribute on the project, but I have very limited knowledge on this space.

**Comment by anderseknert** [comment]
That makes two of us then :) I'm planning to start looking into some of this for a Regal integration soon though, so perhaps we can figure it out together. Starting with some simple issue, like #92 is probably a good idea for getting to know the project, and how to develop for VS Code.

**Comment by anderseknert** [comment]
Adding more and more features via Regal's language server, and "Find All References" will be supported through Regal in the future. Possibly "Go to Defintion" too, but since it's already supported by this extension, it's lower priority. I'll close this here, but feel free to open any request for LSP features in the [Regal repo](https://github.com/styrainc/regal).
